language: node_js
sudo: false
node_js:
- 0.12
env:
- NODE_ENV=travis CXX="g++-4.8" CC="gcc-4.8"
matrix:
  allow_failures:
  - node_js: 4
services:
- mongodb
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
    - clang
before_install:
- gem update --system
- gem install sass --version "=3.3.7"
- npm i nsp -g
- npm install protractor
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- node_modules/protractor/bin/webdriver-manager update --standalone --firefox
- node_modules/protractor/bin/webdriver-manager start 2>&1 &
- sleep 3
after_script:
- nsp audit-package
- grunt coverage
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/249daf9851ea4776f34e
    on_success: change
    on_failure: always
    on_start: never
cache:
  apt: true
  directories:
  - node_modules/
  - public/lib/
deploy:
  provider: heroku
  api_key:
    secure: HRWQW9HlZtbTpQ8o+URfYRNh5Bgm6xxZJ6NRnUaQtSm9t3a88vXUL54OsgMgLTgg2u1N+/+ulfp0vZnnGRNW1z44xGVEVAlsiOYY+n5qUOXBLhMXZA9tao68/kyAQmB/Bfb8Ii4n+4fgyQIrgxoKH1wgCj0/p8szlW8FUUt7CjGboE0LPmyakjTbORKS9gs1HoiyFM/DHOm/P6RvOqMMjGgzeacE+n77Wh2dfmMK2bED4GAJF126Z/+gQ1CIeZFIHcqygIsVQ8CBnGAqRwZ9lsC7+cqaC2enwUBIn3s7FJOjc037ifHju6z0rEImkhMfGoPX+BbSu6PwMqQ1ZMZPL0mPLYpo5E3qwhhI5njJR8ZBuRhWS6U12Vptw2tpwpyqp6uy5WzHOSsVN+3n10F9G19yZrNznfoCNF2ayXgdvtWFEO4rSyrARSzzTVs7/lbCYJ4avIisM+KFBcyc9Bcpn3pRuuSmE3njTR6Ste+AyIKJn/TAPSQpLNqBXEFHYLygTyFSt+IUVyjdVMB4R8xfcirARiQdozMxd7aLJZIiktuoMZmOnS5BjGUOBfqKct+nicC0teg+xL6GEZg1NwkWE97CE4iSQbRHOi+2CnmMcn7Z4rlD7oPYhn+4eo1/Ov2vkov2Ca0fIG8vq39OGkRZi5Cc0xKaJT6bgNnIHDCeldA=
  app: me_irl
  on:
    repo: kmattimo/me_irl
